name: Deploy to NAIS

on:
  workflow_call:
    inputs:
      NAIS_ENV:
        required: true
        type: string
      IMAGE:
        required: true
        type: string

jobs:
  build:
    name: Deploy to NAIS (${{ inputs.NAIS_ENV }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.NAIS_ENV }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.NAIS_ENV }}-gcp
          RESOURCE: .nais/nais.yml
          VAR: image=${{ inputs.IMAGE }}
          VARS: .nais/vars/${{ inputs.NAIS_ENV }}.yml
