name: Post slack notification on main push

on:
  push:
    branches:
      - main

jobs:
  notify:
    name: Notify tiltakspenger-pull-requests
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'Merge pull request') && github.actor != 'dependabot[bot]' }}
    steps:
      - name: Post message
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          curl -X POST --data "{\"text\": \"Push til main: $GITHUB_ACTOR p√• $GITHUB_REPOSITORY - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA - ${{ env.COMMIT_MESSAGE }}\"}" $WEBHOOK_URL